export const funnyGangs: { [key: string]: string } = {
  angels: 'Pombas da Paz',
  insanos: 'Doidões S/A',
  infamous: 'InFamosinhos',
  ballas: 'Boladas',
  hustlers: 'Hustleiros',
  blackrose: 'Flor Trevosa',
  cesarini: 'Césarzinho',
  families: 'Fámílias Reunidas',
  sharksix: 'Tralalero Tralala',
  mib: 'Homens de Preto e Azul',
  anarquia: 'Anarquinhos',
  cyberdystopia: 'Ciber Bagunça',
  thelost: 'Perdidos e Achados',
  vagos: 'Taxistas',
  bandoleros: 'Restaurante Mexicano',
}
